name: PTimeUI
version: 1.0.2
api: 3.0.0
main: supercrafter333\PTimeUI\PTimeLoader
mcpe-protocols:
  - 407
  - 408
  - 419
  - 422
  - 428
  - 431
  - 440
author: supercrafter333

permissions:
  ptimeui.cmd:
    description: Command Permission
    default: op
